SUBJECTS = ["算数", "理科", "国語"]
SUBJECT_EN = {"算数": "Math", "理科": "Science", "国語": "Japanese"}

DIFFICULTY_LEVELS = ["簡単", "普通", "難しい"]
DIFFICULTY_EN = {"簡単": "Easy", "普通": "Normal", "難しい": "Hard"}

MODE_TEN = "TEN_QUESTIONS"
MODE_ENDLESS = "ENDLESS"
MODES = [MODE_TEN, MODE_ENDLESS]

STATE_MENU = "MENU"
STATE_PRELOADING = "PRELOADING"
STATE_PLAYING = "PLAYING"
STATE_CORRECT = "CORRECT"
STATE_GAME_OVER = "GAME_OVER"
STATE_CLEAR = "CLEAR"

MENU_STEP_MODE = "MODE_SELECT"
MENU_STEP_CONFIG = "CONFIG_SELECT"
